### ISSUE TITLE
[Request] Add option to set amounts of specific ball to keep

### ISSUE THREAD

**Issue by Asriandy** [plgonzalezrx8/MagicPoGoBot#1]
Please add options so we can set amount of specific balls that we will keep...
Thank u

**Comment by plgonzalezrx8** [comment]
Noted, will be working on this as well. I have a question for you, do you know that it is optimized to keep the best pokeballs possible? So if you want to have 200 pokeballs, and you have 180 ultra, and 40 great and 30 pokeballs, it will get rid of all the pokeball and 20 great balls.

I can add this feature no problem, but I am wondering why you would like to keep more pokeballs when you can have better ultraballs or great balls.

**Comment by Asriandy** [comment]
Otherwise I really expect to save more greatballs and ultraballs...
But to anticipate the worst in the future, we should keep it to reasonable amounts. Because both items were very rarely obtained and used rather than pokeball.

Sorry for my bad English..

**Comment by plgonzalezrx8** [comment]
@Asriandy Ok, I have a few issues to iron out before I can get to this one, but I'll get to it.

**Comment by r-pearce** [comment]
There is no applicable value to this, due to the logic you describe of it keeping the best balls first. It will add even more clutter to the Config, and reduce the overall effectiveness of the current item recycling prioritization.

**Comment by Asriandy** [comment]
@r-pearce I mean just how I can set the maximum number of each ball that can be saved ... Not matter what the priority ball to be keep first ... 

In the config file only contained "TotalAmountOfPokeballsToKeep"
I mean that that is it possible to add logic functions such as "TotalAmountOfGreatballsToKeep" and "TotalAmountOfUltraballsToKeep"?

I think I've got the solution [/NoxxDev/NecroBot/issues/124](https://github.com/NoxxDev/NecroBot/issues/124)

Thank u

**Comment by plgonzalezrx8** [comment]
I think that due to the current status of the algorithm to keep ultra balls priority, this doesn't need to be changed.
