### ISSUE TITLE
Walking speed random question

### ISSUE THREAD

**Issue by dillusi** [plgonzalezrx8/MagicPoGoBot#11]
I would like to ask about the config speed for this:

 "WalkingSpeedInKilometerPerHour": 3.16,
    "RandomMinWalkingSpeed": 1.2,
    "RandomMaxWalkingSpeed": 2.2,
    "UseWalkingSpeedVariant": true,
    "ShowVariantWalking": true,
    "RandomlyPauseAtStops": true,

May I know 
    **"RandomMinWalkingSpeed": 1.2,
    "RandomMaxWalkingSpeed": 2.2,**

How does the random min and max walking speed works? As I noticed that there is some possibility that the walking speed can be more than the one I have set (3.16km/h).
![qq 20160814223530](https://cloud.githubusercontent.com/assets/20932640/17743537/9e005930-64d6-11e6-9139-0558a0a60a33.png)

Thanks.

**Comment by Tokariew** [comment]
WalkingSpeed is your starting speed now
randommin is how much will your starting value decrease
randommax how much speed will increase from starting value

so bot will go from 2.96 to 5.36 in this settings, and should keep avg speed around 3.16

**Comment by plgonzalezrx8** [comment]
What @Tokariew said is correct, let me know if there's any other questions you have.
