### ISSUE TITLE
crash ( with a restart - (asked to post here by Plgonzalezrx8)

### ISSUE THREAD

**Issue by joehsmash** [plgonzalezrx8/MagicPoGoBot#18]
Expected Behavior

Necrobot 0.90 to not throw random errors

Actual Behavior

tosses up a random error every once in a while, unsure what causes it. tried to recreate my config.json, and my auth.json to no avail. also checked that they were valid json's through posted website. This started happening once it auto-updated to 0.90. Also couldnt find any reports of this which leads me to believe that its only me?

23:16:00 Walking Speed: Has been changed, 45.61 Km/h to 44.87 Km/h
23:16:01 Walking Speed: Has been changed, 44.87 Km/h to 46.02 Km/h
23:16:03 Name: The Lake in the Forest XP: 50, Gems: 0, Items: 2 x ItemPokeBall, 1 x ItemGreatBall, Lat: 49.239576, Long: -122.880763
23:16:03 Pokemon Servers might be offline / unstable. Trying again...
23:16:04 Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
at System.Collections.Generic.List`1.get_Item(Int32 index)
at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at PoGo.NecroBot.Logic.State.FarmState.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at PoGo.NecroBot.Logic.State.StateMachine.d__3.MoveNext()
23:16:04 Logging in using Google
23:16:06 Playing as 
23:16:06 Make sure Lat & Lng are right. Exit Program if not! Lat: 49.2395760004574 Lng: -122.880762999272

Your config.json

your config here

http://pastebin.com/SGWKZbN5

Steps to Reproduce

unknown

Other Information

Version:0.90
Windows Version:64 bit win 10 (home)
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
causes a kick from the servers, necro logs back in and its business as usual.

also curious where we can make a suggestion for an addition to the program?

also just a note on this my 0.90  (necrobot) didnt update to the 0,91.

**Comment by Unentertained** [comment]
Create an Issue with [Feature Request] in the beginning of the title to submit ideas.
Also, next time, please use pastebin instead of inserting a wall of text. :)
Your Config - http://pastebin.com/D4NT2tdG

**Comment by joehsmash** [comment]
oh ok ill fix it

**Comment by Unentertained** [comment]
Just a suggestion (not related to the crash), your config should be changed. In my opinion, you are highly likely to be banned soon. Walking speed is almost 28 MPH and the delay between catching is 1/10 of a second. Again just a friendly suggestion :)

**Comment by Unentertained** [comment]
Found the problem! Change your "MaxTravelDistanceInMeters".
It's currently 62,1371 Miles. And the earth is only around 7,917 Miles wide.

**Comment by Unentertained** [comment]
[Close Issue]

**Comment by joehsmash** [comment]
great that you found the issue, this config was generated by the script, so this wasnt anything that i changed. but ill be sure to change it right now and and check.

also about the walking speed, this is on an alt character that i started just to test the limits of the speed.

**Comment by Tokariew** [comment]
i think it kind of similar with my issue posted here: https://github.com/plgonzalezrx8/MagicPoGoBot/issues/17  but i have only 400 metres of Travel Distance

**Comment by joehsmash** [comment]
also another point, there are a lot of people who drive around and play, or play while theyre on a bus. its not really that un likely that people can travel at 45km an hour  and still play.

**Comment by Tokariew** [comment]
This error only appear when you get info about unstable servers, so probably it's related only to connection with niantic servers.

ok, my issue is diffrent, after expection it's killed program

**Comment by joehsmash** [comment]
no, this error just appears randomly 

[19:27:20] (POKESTOP) Name: Heritage Paré Residence XP: 50, Gems: 0, Items: 1 x ItemRazzBerry, 1 x ItemPokeBall, 1 x ItemRevive, Lat: 49.241228, Long: -122.859544
[19:27:20] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[19:27:21] (ERROR) Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext()

**Comment by plgonzalezrx8** [comment]
If that is the config that you are using, it is not the correct one and it wasn't recreated correctly, the format is off. Completely delete the config and auth files and start the necro bot from scratch. Format should look like this.



{
  "ConsoleSettings": {
    "TranslationLanguageCode": "en",
    "StartupWelcomeDelay": false,
    "AmountOfPokemonToDisplayOnStart": 10,
    "DetailedCountsBeforeRecycling": true
  },
  "UpdateSettings": {
    "CheckForUpdates": true,
    "AutoUpdate": true,
    "TransferConfigAndAuthOnUpdate": true
  },
  "WebsocketsSettings": {
    "UseWebsocket": false,
    "WebSocketPort": 14251
  },
  "LocationSettings": {
    "DisableHumanWalking": false,
    "DefaultLatitude": 40.785092,
    "DefaultLongitude": -73.968286,
    "WalkingSpeedInKilometerPerHour": 40.0,
    "RandomMinWalkingSpeed": 4.0,
    "RandomMaxWalkingSpeed": 4.0,
    "UseWalkingSpeedVariant": true,
    "ShowVariantWalking": true,
    "RandomlyPauseAtStops": true,
    "MaxSpawnLocationOffset": 10,
    "MaxTravelDistanceInMeters": 1000
  },
  "TelegramSettings": {
    "UseTelegramAPI": false,
    "TelegramAPIKey": null,
    "TelegramPassword": "12345"
  },
  "GPXSettings": {
    "UseGpxPathing": false,
    "GpxFile": "GPXPath.GPX"
  },
  "SnipingSettings": {
    "UseSnipeLocationServer": false,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": false,
    "GetOnlyVerifiedSniperInfoFromPokezz": true,
    "GetSniperInfoFromPokeSnipers": true,
    "GetSniperInfoFromPokeWatchers": true,
    "GetSniperInfoFromSkiplagged": true,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false
  },
  "PokemonSettings": {
    "CatchPokemon": true,
    "DelayBetweenPokemonCatch": 2000,
    "UseIncenseConstantly": false,
    "UseEggIncubators": true,
    "UseEggIncubatorMinKm": 2,
    "UseLuckyEggConstantly": false,
    "UseLuckyEggsMinPokemonAmount": 30,
    "UseLuckyEggsWhileEvolving": false,
    "UseBerriesMinCp": 1000,
    "UseBerriesMinIv": 90.0,
    "UseBerriesBelowCatchProbability": 0.2,
    "UseBerriesOperator": "or",
    "MaxBerriesToUsePerPokemon": 3,
    "TransferWeakPokemon": false,
    "TransferDuplicatePokemon": true,
    "TransferDuplicatePokemonOnCapture": true,
    "RenamePokemon": false,
    "RenameOnlyAboveIv": true,
    "RenameTemplate": "{1}_{0}",
    "FavoriteMinIvPercentage": 95.0,
    "AutoFavoritePokemon": false,
    "MaxPokeballsPerPokemon": 6,
    "UseGreatBallAboveCp": 1000,
    "UseUltraBallAboveCp": 1250,
    "UseMasterBallAboveCp": 1500,
    "UseGreatBallAboveIv": 85.0,
    "UseUltraBallAboveIv": 95.0,
    "UseGreatBallBelowCatchProbability": 0.2,
    "UseUltraBallBelowCatchProbability": 0.1,
    "UseMasterBallBelowCatchProbability": 0.05,
    "AutomaticallyLevelUpPokemon": false,
    "OnlyUpgradeFavorites": true,
    "UseLevelUpList": true,
    "AmountOfTimesToUpgradeLoop": 5,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 95.0,
    "UpgradePokemonMinimumStatsOperator": "and",
    "EvolveAboveIvValue": 95.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
    "KeepPokemonsThatCanEvolve": false,
    "KeepMinCp": 1250,
    "KeepMinIvPercentage": 90.0,
    "KeepMinLvl": 6,
    "KeepMinOperator": "or",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": false,
    "KeepMinDuplicatePokemon": 1,
    "UsePokemonToNotCatchFilter": false,
    "UsePokemonSniperFilterOnly": false,
    "DumpPokemonStats": false
  },
  "RecycleSettings": {
    "VerboseRecycling": true,
    "RecycleInventoryAtUsagePercentage": 90.0,
    "RandomizeRecycle": false,
    "RandomRecycleValue": 5,
    "DelayBetweenRecycleActions": false,
    "TotalAmountOfPokeballsToKeep": 120,
    "TotalAmountOfPotionsToKeep": 80,
    "TotalAmountOfRevivesToKeep": 60,
    "TotalAmountOfBerriesToKeep": 50
  },
  "CustomCatchSettings": {
    "EnableHumanizedThrows": true,
    "EnableMissedThrows": false,
    "ThrowMissPercentage": 25,
    "NiceThrowChance": 40,
    "GreatThrowChance": 30,
    "ExcellentThrowChance": 10,
    "CurveThrowChance": 90,
    "ForceGreatThrowOverIv": 90.0,
    "ForceExcellentThrowOverIv": 95.0,
    "ForceGreatThrowOverCp": 1000,
    "ForceExcellentThrowOverCp": 1500


See the different indentation compared to yours? That config was not done by my bot.

**Comment by plgonzalezrx8** [comment]
Again, that config was NOT generated by my script. Maybe you made an error somewhere. Thanks @Unentertained  for finding the issue, proves that the config was not generated by my bot since thats not a default value.
