### ISSUE TITLE
Pokemon Catch Flee

### ISSUE THREAD

**Issue by Asriandy** [plgonzalezrx8/MagicPoGoBot#5]
Any idea for this?
Only looting pokestop but pokemon always flee

![ss](https://cloud.githubusercontent.com/assets/20786218/17732412/783b5336-6426-11e6-96a1-232a05defba3.png)

**Comment by AmazingGamerBoy** [comment]
You there have a soft ban. I had to wait 24 hours before mine got removed and i could play again

**Comment by Asriandy** [comment]
Ok...
Should wait for tomorrow...
Hope not getting perma ban...
Thank u

**Comment by plgonzalezrx8** [comment]
Thats one type of soft ban, try not to use the bot for 24+ hours.
