### ISSUE TITLE
Soft Bans and No Pokestops found

### ISSUE THREAD

**Issue by mhicarl** [plgonzalezrx8/MagicPoGoBot#7]
Hi, im not familiar with the codes but i look some issues that are the same as mine. Ive tried to use the suggested solution like turning false in snipping things but my problem didnt solved. please help and guide me. thanks a lot

**Comment by philip2705** [comment]
Unban method is to wait 24 hours

**Comment by mhicarl** [comment]
Oh i see thanks for the respond. I dont know why some other people who used this also didnt get soft bans unlike me.. :( my 4 accts get banned in just 2 days i dont know why and i think im doing bot wrong but no idea how to use it well :(
